packages:
  - "apps/*"
  - "services/*"
  - "packages/*"
  - "vendor/ggui/*"

verifyDepsBeforeRun: false
strictDepBuilds: false
autoInstallPeers: true
minimumReleaseAgeExclude:
  - '@ggui-ai/*'
allowBuilds:
  '@google/genai': true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
